import {
  generateSchedule,
  type Loan,
  type LoanInput,
  type RepaymentObligation,
} from "@/lib/domain/scheduler"

/**
 * Loan book.
 *
 * Obligation ladders are generated by the real scheduler rather than
 * hand-written, so the amortisation maths on screen is the maths the engine
 * would actually produce.
 */

interface Seed {
  loan: Loan
  input: LoanInput
  /** Payments already applied, oldest obligation first. */
  paid: number
}

const SEEDS: Seed[] = [
  {
    loan: {
      id: "LN-2024-1247",
      customerId: "BRW001",
      customerName: "Adewale Johnson",
      amount: 600_000,
      interestRate: 0.24,
      tenureMonths: 6,
      repaymentFrequency: "MONTHLY",
      amortizationType: "DECLINING_BALANCE",
      disbursementDate: "2026-01-27",
      state: "IN_RECOVERY",
      productName: "Retail Salary Loan",
      organisationId: "org_vfd",
    },
    input: {
      customerId: "BRW001",
      amount: 600_000,
      interestRate: 0.24,
      tenureMonths: 6,
      repaymentFrequency: "MONTHLY",
      amortizationType: "DECLINING_BALANCE",
      disbursementDate: "2026-01-27",
    },
    paid: 400_000,
  },
  {
    loan: {
      id: "LN-2024-1302",
      customerId: "BRW002",
      customerName: "Ngozi Adeyemi",
      amount: 1_200_000,
      interestRate: 0.3,
      tenureMonths: 6,
      repaymentFrequency: "MONTHLY",
      amortizationType: "FLAT",
      disbursementDate: "2026-01-22",
      state: "IN_RECOVERY",
      productName: "SME Working Capital",
      organisationId: "org_vfd",
    },
    input: {
      customerId: "BRW002",
      amount: 1_200_000,
      interestRate: 0.3,
      tenureMonths: 6,
      repaymentFrequency: "MONTHLY",
      amortizationType: "FLAT",
      disbursementDate: "2026-01-22",
    },
    paid: 260_000,
  },
  {
    loan: {
      id: "LN-2024-1355",
      customerId: "BRW003",
      customerName: "Aisha Mohammed",
      amount: 800_000,
      interestRate: 0.26,
      tenureMonths: 4,
      repaymentFrequency: "MONTHLY",
      amortizationType: "DECLINING_BALANCE",
      disbursementDate: "2026-03-05",
      state: "PARTIALLY_RECOVERED",
      productName: "Retail Salary Loan",
      organisationId: "org_vfd",
    },
    input: {
      customerId: "BRW003",
      amount: 800_000,
      interestRate: 0.26,
      tenureMonths: 4,
      repaymentFrequency: "MONTHLY",
      amortizationType: "DECLINING_BALANCE",
      disbursementDate: "2026-03-05",
    },
    paid: 320_000,
  },
  {
    loan: {
      id: "LN-2024-1401",
      customerId: "BRW004",
      customerName: "Chidinma Obi",
      amount: 2_000_000,
      interestRate: 0.22,
      tenureMonths: 12,
      repaymentFrequency: "MONTHLY",
      amortizationType: "BULLET",
      disbursementDate: "2026-01-09",
      state: "IN_RECOVERY",
      productName: "Asset Finance",
      organisationId: "org_vfd",
    },
    input: {
      customerId: "BRW004",
      amount: 2_000_000,
      interestRate: 0.22,
      tenureMonths: 12,
      repaymentFrequency: "MONTHLY",
      amortizationType: "BULLET",
      disbursementDate: "2026-01-09",
    },
    paid: 110_000,
  },
  {
    loan: {
      id: "LN-28471",
      customerId: "BRW005",
      customerName: "Emeka Okafor",
      amount: 450_000,
      interestRate: 0.28,
      tenureMonths: 3,
      repaymentFrequency: "MONTHLY",
      amortizationType: "FLAT",
      disbursementDate: "2026-04-14",
      state: "IN_RECOVERY",
      productName: "Micro Loan",
      organisationId: "org_lender_a",
    },
    input: {
      customerId: "BRW005",
      amount: 450_000,
      interestRate: 0.28,
      tenureMonths: 3,
      repaymentFrequency: "MONTHLY",
      amortizationType: "FLAT",
      disbursementDate: "2026-04-14",
    },
    paid: 0,
  },
  {
    loan: {
      id: "LN-28502",
      customerId: "BRW006",
      customerName: "Tunde Bakare",
      amount: 300_000,
      interestRate: 0.25,
      tenureMonths: 3,
      repaymentFrequency: "MONTHLY",
      amortizationType: "DECLINING_BALANCE",
      disbursementDate: "2026-05-02",
      state: "OVERDUE",
      productName: "Micro Loan",
      organisationId: "org_vfd",
    },
    input: {
      customerId: "BRW006",
      amount: 300_000,
      interestRate: 0.25,
      tenureMonths: 3,
      repaymentFrequency: "MONTHLY",
      amortizationType: "DECLINING_BALANCE",
      disbursementDate: "2026-05-02",
    },
    paid: 105_000,
  },
  {
    loan: {
      id: "LN-28560",
      customerId: "BRW007",
      customerName: "Halima Sule",
      amount: 1_800_000,
      interestRate: 0.32,
      tenureMonths: 6,
      repaymentFrequency: "MONTHLY",
      amortizationType: "FLAT",
      disbursementDate: "2025-11-28",
      state: "IN_RECOVERY",
      productName: "SME Working Capital",
      organisationId: "org_vfd",
    },
    input: {
      customerId: "BRW007",
      amount: 1_800_000,
      interestRate: 0.32,
      tenureMonths: 6,
      repaymentFrequency: "MONTHLY",
      amortizationType: "FLAT",
      disbursementDate: "2025-11-28",
    },
    paid: 120_000,
  },
  {
    loan: {
      id: "LN-28611",
      customerId: "BRW008",
      customerName: "Segun Adebayo",
      amount: 900_000,
      interestRate: 0.2,
      tenureMonths: 3,
      repaymentFrequency: "MONTHLY",
      amortizationType: "DECLINING_BALANCE",
      disbursementDate: "2026-04-30",
      state: "CLOSED",
      productName: "Retail Salary Loan",
      organisationId: "org_lender_a",
    },
    input: {
      customerId: "BRW008",
      amount: 900_000,
      interestRate: 0.2,
      tenureMonths: 3,
      repaymentFrequency: "MONTHLY",
      amortizationType: "DECLINING_BALANCE",
      disbursementDate: "2026-04-30",
    },
    paid: 999_999_999, // fully settled
  },
]

const REFERENCE_DATE = new Date("2026-08-06T09:00:00Z")

function build() {
  const loans: Loan[] = []
  const obligations: Record<string, RepaymentObligation[]> = {}

  for (const seed of SEEDS) {
    loans.push(seed.loan)
    const schedule = generateSchedule(seed.loan.id, seed.input, REFERENCE_DATE)

    // Apply the seeded payment oldest-first, then mark anything still
    // outstanding and past due as DEFAULTED so the queues have real state.
    let remaining = seed.paid
    const applied = schedule.map((ob) => {
      let outstanding = ob.outstandingAmount
      let status = ob.status

      if (remaining > 0) {
        if (remaining >= outstanding) {
          remaining -= outstanding
          outstanding = 0
          status = "PAID"
        } else {
          outstanding = Math.round((outstanding - remaining) * 100) / 100
          remaining = 0
          status = "PARTIALLY_PAID"
        }
      }

      if (outstanding > 0) {
        const due = new Date(ob.dueDate)
        if (due < REFERENCE_DATE) {
          status = status === "PARTIALLY_PAID" ? "PARTIALLY_PAID" : "DEFAULTED"
        } else {
          status = "PENDING"
        }
      }

      return { ...ob, outstandingAmount: outstanding, status }
    })

    obligations[seed.loan.id] = applied
  }

  return { loans, obligations }
}

const built = build()

export const LOANS: Loan[] = built.loans
export const OBLIGATIONS: Record<string, RepaymentObligation[]> = built.obligations

export function loanById(id: string): Loan | undefined {
  return LOANS.find((l) => l.id === id)
}

export function obligationsFor(loanId: string): RepaymentObligation[] {
  return OBLIGATIONS[loanId] ?? []
}

export const LOAN_REFERENCE_DATE = REFERENCE_DATE
